set nocompatible
" enable syntax and plugins
syntax enable
filetype plugin on

set number
set relativenumber

set incsearch
set ignorecase

set shell=powershell

" mappings
let g:mapleader = ","

" plugins
call plug#begin()

	Plug 'tpope/vim-sensible'

	Plug 'tpope/vim-dadbod'
	Plug 'kristijanhusak/vim-dadbod-completion'
	Plug 'kristijanhusak/vim-dadbod-ui'

	Plug 'OmniSharp/omnisharp-vim'

	Plug 'dense-analysis/ale'
	Plug 'puremourning/vimspector'

call plug#end()

let g:OmniSharp_server_stdio = 1


" Tell ALE to use OmniSharp for linting C# files, and no other linters.
let g:ale_linters = { 'cs': ['OmniSharp'] }

" search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when we tab complete
set wildmenu
